baseURL = "http://rosagriculture.org/"
title = "ROSA"

enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

 # First one is picked as the Twitter card image if not set on page.
 #images = ["images/project-illustration.png"]

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
#id = "UA-00000000-0"

# Language configuration

[languages]
[languages.en]
title = "ROS Agriculture"
description = "An ecosystem to empower farmers with robotic tools."
languageName ="English"
# Weight used for sorting.
weight = 1
#[languages.no]
#title = "ROS Agriculture"
#description = "Empowering the farmers"
#languageName ="Norsk"
#contentDir = "content/no"
time_format_default = "02.01.2006"
time_format_blog = "02.01.2006"


# Everything below this are Site Params

[params]
copyright = "ROS Agriculture"
privacy_policy = ""
github_repo = "https://github.com/ros-agriculture/ros-a"

# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "002714214824939399291:5_ltfhcysmc"

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name ="Twitter"
	url = "https://twitter.com/ROSAgriculture"
	icon = "fab fa-twitter"
        desc = "Follow us on Twitter to get the latest news"
[[params.links.user]]
	name ="Facebook"
	url = "https://facebook.com/ROSAgriculture"
	icon = "fab fa-facebook"
        desc = "Follow us on Facebook to get the latest stories"
[[params.links.user]]
	name = "Slack"
	url = "http://rosagriculture.slack.com"
	icon = "fab fa-slack"
        desc = "Discussion and help from your fellow users"

# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "Slack"
	url = "http://rosagriculture.slack.com"
	icon = "fab fa-slack"
        desc = "Chat with other project contributors"
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/ros-agriculture"
	icon = "fab fa-github"
        desc = "Development takes place here!"
