name: Hugo

on:
  push:
    branches: [ hugo ]
  pull_request:
    branches: [ hugo ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.62.2'
          extended: true

      - name: Install Node dependencies
        run: npm install
        
      - name: Build
        run: hugo --config config.toml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Copycat
        uses: andstor/copycat-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          src_path: /.
          dst_owner: ros-agriculture
          dst_repo_name: ros-agriculture.github.io
          dst_branch: master
          src_branch: gh-pages
